sudo: false
language: go
go:
  - 1.3
  - tip
before_install:
  - make tools
install:
  - go get github.com/jeffail/gabs
  - go get github.com/mitchellh/packer/common
  - go get github.com/mitchellh/packer/packer
  - go get github.com/mitchellh/packer/packer/plugin
script:
  - make lint style test build
