sudo: false
language: go
node_js:
  - 1.3
  - tip
install:
  - go get github.com/jeffail/gabs
  - go get github.com/mitchellh/packer/common
  - go get github.com/mitchellh/packer/packer
  - go get github.com/mitchellh/packer/packer/plugin
script:
  - go test
  - go build
